% Author: Zhao Mingxin
% Date: 2018/12/27
% Description: Load parameters from JSON file generated by Flatc
% intepreter. More details pls refer to Google Flatc buffer API.

function res = readJSON(path)
    fprintf(2,'Loading parameters from JSON file.\n');
    res = jsondecode(fileread(path));
    fprintf(2,'Parameters Loaded.\n');
end